In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.5'

## reverse

In [3]:
myarray = np.array([1,2,3])
myarray[::-1]

array([3, 2, 1])

In [4]:
myarray = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
myarray[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

## scientific notation

In [11]:
np.set_printoptions(edgeitems=3,infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

y=np.array([1.0e-10,1.0,100,1000])
y

array([1.e-10, 1.e+00, 1.e+02, 1.e+03])

In [13]:
np.set_printoptions(suppress=True)
y

array([   0.,    1.,  100., 1000.])

## selecting

In [ ]:
myarray = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
myarray

In [ ]:
myarray[:,1]

In [ ]:
myarray[0,:]

In [ ]:
x = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
y = x.copy()

In [ ]:
y.fill(1)

In [ ]:
x

In [ ]:
y

## add row to multimensional array

In [ ]:
myarray = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
newrow = np.array([9,9,9])

In [ ]:
np.vstack([myarray,newrow])

## add column

In [ ]:
myarray = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
newcol = np.array([[9],[9]])

In [ ]:
np.hstack([myarray,newcol])