In [1]:
import numpy as np
import scipy.stats as st

In [2]:
np.random.uniform(low=0,high=1,size=10)

array([0.6121605 , 0.92820148, 0.93332527, 0.16753144, 0.19179762,
       0.84345473, 0.20927801, 0.91009622, 0.80663204, 0.17651168])

In [3]:
np.random.randint(low=0, high=100, size=10)


array([85, 85, 93, 22, 81, 44, 41, 64, 91, 64])

In [9]:
dist = st.norm(loc=0.0,scale=1.0)
dist.rvs(10)

array([-1.20379751, -0.08901484, -0.44583519,  1.4620899 , -0.03970467,
       -0.56142861,  1.74105897,  0.59947225,  1.97756661,  1.40423881])

In [5]:
dist = st.norm(loc=0.0,scale=1.0)
dist.pdf(1.645)

0.10311081109198142

In [6]:
dist.cdf(1.645)

0.9500150944608786