In [7]:
import numpy as np
import scipy.stats as st

In [5]:
np.random.uniform(low=0,high=1,size=10)

array([ 0.88395329,  0.38237895,  0.18446876,  0.43672405,  0.37831267,
        0.72839052,  0.51533127,  0.97796012,  0.25615201,  0.24436513])

In [6]:
np.random.randint(low=0, high=100, size=10)


array([92, 95, 57,  6, 26, 86, 55, 46, 29, 62])

In [15]:
dist = st.norm(loc=0.0,scale=1.0)
x = np.array([-0.5,0.,0.5])
dist.pdf(x)

array([ 0.35206533,  0.39894228,  0.35206533])

In [17]:
dist = st.norm(loc=0.0,scale=1.0)
dist.pdf(1.645)

0.10311081109198142

In [19]:
dist.cdf(1.645)

0.95001509446087862