In [135]:
import torch
import numpy as np
from platform import python_version
from torchvision.models import resnet18, ResNet18_Weights
from torch import nn,optim
import torch.nn.functional as F

In [7]:
python_version(), np.__version__, torch.__version__

('3.8.10', '1.23.5', '1.13.0+cpu')

In [16]:
data = [[1,2],[3,4]]

In [17]:
data

[[1, 2], [3, 4]]

In [18]:
x_data = torch.tensor(data)

In [19]:
x_data

tensor([[1, 2],
        [3, 4]])

In [14]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [20]:
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [22]:
x_data == x_np

tensor([[True, True],
        [True, True]])

In [25]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [36]:
shape = (2,3)

In [37]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.2861, 0.1193],
        [0.6123, 0.3941]])

In [38]:
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.4561, 0.7145, 0.0928],
        [0.0309, 0.3934, 0.3822]])

In [39]:
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.1840, 0.5762, 0.6003],
        [0.0338, 0.8488, 0.5970]])

In [41]:
zeros = torch.zeros(shape)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [42]:
tensor = torch.rand(3,4)

In [43]:
tensor

tensor([[0.4018, 0.6281, 0.4420, 0.3289],
        [0.2644, 0.7828, 0.2750, 0.4936],
        [0.5191, 0.2584, 0.5921, 0.4341]])

In [44]:
tensor.shape

torch.Size([3, 4])

In [45]:
tensor.dtype

torch.float32

In [47]:
tensor.device

device(type='cpu')

In [48]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print('now on cuda')

In [49]:
tensor.device

device(type='cpu')

In [55]:
tensor = torch.tensor([[1,2,3,4],[5,6,7,8]])
tensor

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [56]:
tensor[:,[2,3]]

tensor([[3, 4],
        [7, 8]])

In [57]:
tensor1 = torch.tensor([
    [1,2],
    [3,4]
])

tensor2 = torch.tensor([
    [9,9],
    [9,9]
])

In [58]:
torch.cat([tensor1,tensor2],dim=1)

tensor([[1, 2, 9, 9],
        [3, 4, 9, 9]])

In [59]:
torch.cat([tensor1,tensor2],dim=0)

tensor([[1, 2],
        [3, 4],
        [9, 9],
        [9, 9]])

In [60]:
tensor1 * tensor2

tensor([[ 9, 18],
        [27, 36]])

In [61]:
tensor1.mul(tensor2)

tensor([[ 9, 18],
        [27, 36]])

In [64]:
tensor1.matmul(tensor2)

tensor([[27, 27],
        [63, 63]])

In [66]:
tensor1.matmul_(tensor2)

AttributeError: 'Tensor' object has no attribute 'matmul_'

In [68]:
tensor2.numpy()

array([[9, 9],
       [9, 9]])

In [69]:
tensor2

tensor([[9, 9],
        [9, 9]])

## autograd

In [72]:
model  = resnet18(weights=ResNet18_Weights.DEFAULT)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /home/felipe/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100.0%


In [73]:
data = torch.rand(1,3,64,64)

In [77]:
data.shape

torch.Size([1, 3, 64, 64])

In [118]:
labels = torch.rand(1,10)

In [80]:
labels.shape

torch.Size([1, 1000])

In [81]:
prediction = model(data)

In [83]:
prediction.shape

torch.Size([1, 1000])

In [84]:
residuals = (prediction - labels).sum()
residuals.shape

torch.Size([])

In [86]:
residuals.backward()

In [89]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.01,momentum=0.9)

In [101]:
optimizer.step()

## finetuning

In [103]:
model = resnet18(weights=ResNet18_Weights.DEFAULT)

In [104]:
for param in model.parameters():
    param.requires_grad = False

In [108]:
print(model)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [113]:
model.fc = nn.Linear(512,10)

In [114]:
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

In [115]:
prediction = model(data)

In [117]:
prediction.shape

torch.Size([1, 10])

In [119]:
residuals = (prediction - labels).sum()

In [122]:
residuals

tensor(-4.7043, grad_fn=<SumBackward0>)

In [120]:
residuals.backward()

In [121]:
optimizer.step()

In [123]:
prediction = model(data)

In [124]:
residuals = (prediction - labels).sum()

In [126]:
residuals

tensor(-50.9314, grad_fn=<SumBackward0>)

In [127]:
residuals.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [128]:
optimizer.step()

In [129]:
prediction = model(data)
residuals = (prediction - labels).sum()
residuals

tensor(-184.9902, grad_fn=<SumBackward0>)

In [131]:
residuals.backward()
optimizer.step()

In [132]:
prediction = model(data)
residuals = (prediction - labels).sum()
residuals

tensor(-444.3246, grad_fn=<SumBackward0>)

In [133]:
residuals.backward()
optimizer.step()

In [134]:
prediction = model(data)
residuals = (prediction - labels).sum()
residuals

tensor(-862.6343, grad_fn=<SumBackward0>)

## neural nets

In [202]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()

        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,16,5)

        self.fc1 = nn.Linear(16 * 5 * 5,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
    
    
    def forward(self, x):
        
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
        
        x = torch.flatten(x,1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        
        x = self.fc3(x)
        
        return x
    
net = Net()
   

In [203]:
input = torch.randn(1, 1, 32, 32)

In [204]:
prediction = net(input)

In [205]:
prediction

tensor([[ 0.1293,  0.0025, -0.0632,  0.0977,  0.1390,  0.0253, -0.0441, -0.0228,
          0.0991, -0.1008]], grad_fn=<AddmmBackward0>)

In [206]:
dummy_targets = torch.ones_like(prediction)
dummy_targets

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [207]:
criterion = nn.MSELoss()

In [208]:
loss = criterion(prediction,dummy_targets)
loss

tensor(0.9549, grad_fn=<MseLossBackward0>)

In [209]:
net.zero_grad()

In [210]:
net.conv1.bias

Parameter containing:
tensor([-0.1335, -0.1473, -0.0162,  0.0798,  0.1532, -0.0693],
       requires_grad=True)

In [211]:
net.conv1.bias.grad

In [212]:
loss.backward()

In [213]:
net.conv1.bias

Parameter containing:
tensor([-0.1335, -0.1473, -0.0162,  0.0798,  0.1532, -0.0693],
       requires_grad=True)

In [214]:
net.conv1.bias.grad

tensor([-0.0139, -0.0102, -0.0108, -0.0052,  0.0099, -0.0002])

In [215]:
optimizer = optim.SGD(net.parameters(),lr=0.01)

loop this

In [268]:
optimizer.zero_grad()
output = net(input)
loss = criterion(output,dummy_targets)
print(f"loss is {loss}")
loss.backward()
optimizer.step()

loss is 0.00022716645617038012


In [269]:
net(input)

tensor([[1.0134, 1.0145, 1.0003, 1.0127, 1.0134, 0.9788, 0.9948, 0.9959, 0.9904,
         0.9765]], grad_fn=<AddmmBackward0>)