In [9]:
np.__version__

'1.18.2'

In [3]:
import numpy as np

np.random.choice(10,size=5)

array([3, 3, 7, 7, 2])

In [4]:
import numpy as np

names = ["alice", "bob", "charlie", "david"]

np.random.choice(names,size=2,replace=False)

array(['charlie', 'alice'], dtype='<U7')

In [5]:
import numpy as np

np.random.choice(10,size=5)


array([5, 3, 0, 6, 8])

In [7]:
np.random.uniform(low=-5,high=5,size=10)

array([-1.52197428e+00,  5.08109762e-01,  2.96426560e+00,  3.17985813e+00,
       -4.54695283e+00, -4.33826344e-01,  1.74998558e-03, -1.91757002e+00,
        4.67157356e+00, -4.38634184e+00])

In [31]:
import numpy as np

names = ["alice", "bob", "charlie", "david", "edward", "filip"]

np.random.choice(names, size=3, replace=True, p=[0.4, 0.2, 0.2, 0.2, 0.0, 0.0])

array(['charlie', 'alice', 'alice'], dtype='<U7')