In [3]:
import numpy as np

In [4]:

arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2 = np.array([[1,1,1],[0,0,0]])
arr2

array([[1, 1, 1],
       [0, 0, 0]])

In [6]:
np.sum(arr2,axis=0)

array([1, 1, 1])

In [7]:
np.sum(arr2,axis=1)

array([3, 0])

In [9]:
np.sum(arr2)

3

In [10]:
arr2.sum()

3