In [1]:
import numpy as np

In [9]:
np.random.choice(10,10,replace=False)

array([0, 3, 9, 5, 1, 4, 8, 6, 2, 7])

In [6]:
np.random.randint(low=0, high=10, size=10)

array([2, 8, 2, 7, 7, 9, 1, 7, 9, 5])

In [12]:
    arr = [1,2,3,4,5,6,7,8,9]

    np.random.choice(arr,size=5,replace=False)
    

array([8, 2, 7, 5, 1])

In [11]:
elems

array([9, 7, 1, 6, 5])