In [1]:
import numpy as np

np.random.seed(42)

In [2]:
arr = np.arange(0,100,1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
np.random.seed(42)
np.random.choice(arr,10)

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [6]:
np.random.seed(42)
np.random.choice(arr,10)

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [7]:
np.random.choice(arr,10)

array([87, 99, 23,  2, 21, 52,  1, 87, 29, 37])

In [8]:
np.random.choice(arr,10)

array([ 1, 63, 59, 20, 32, 75, 57, 21, 88, 48])